### ISSUE TITLE
 Redis version needs to be updated as 4.0 is retiring.

### ISSUE THREAD

**Issue by SandraAhlgrimm** [Azure-Samples/apptemplates-microservices-spring-app-on-AzureSpringApps#21]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
```bash
az deployment group create \
 -g $RESOURCE_GROUP \
 -f iac/bicep/services-main.bicep \
 --parameters location=$REGION \
  projectName=$PROJECT_NAME \
  database_name=$MYSQL_DATABASE_NAME \
  mysql_adminUsername=$MYSQL_SERVER_ADMIN_NAME \
  mysql_adminPassword=$MYSQL_SERVER_ADMIN_PASSWORD \
  servicePrincipal="{ \"clientId\": \"$AZURE_CLIENT_ID\", 
  \"tenantId\": \"$AZURE_TENANT_ID\", 
  \"objectId\": \"$AZURE_OBJECT_ID\" }"
``` 

### Any log messages given by the failure
>
(...) .Resources/deployments/create-redis","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidRequestBody","message":"Cannot create cache. Redis version 4.0 is retiring. Please see https://aka.ms/RedisVersionRetirementTimelines for more information.

### Expected/desired behavior
> deployment should be successful

**Comment by euchungmsft** [comment]
Updated to 'latest'
